import { Injectable } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { HotToastService } from '@ngneat/hot-toast';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

import { API_ENDPOINT, HTTP_HEADERS, FINAL } from '@app/config/constants';

@Injectable({
  providedIn: 'root',
})
export class EditorService {
  private apiURL = API_ENDPOINT;
  httpOptions = { headers: new HttpHeaders(HTTP_HEADERS) };
  public finalArray: any[] = [];
  public headerArray: any[] = [];
  public isHidden!: boolean;
  public iconButton = false;
  public image = false;
  public header = false;
  public description = false;
  public input = false;
  public dropdown = false;
  public appHeader = false;
  public slimEditorEdit = false;
  public spacer = false;
  public plainTextEdit = false;
  public expandingTextEdit = false;

  constructor(
    public fb: FormBuilder,
    private http: HttpClient,
    private toasty: HotToastService
  ) {}

  public createBaseComponent(image: any): any {
    return this.fb.group({
      id: '',
      component: 'image',
      Text: '',
      TextSize: '32',
      TextAlignment: 'start',
      ButtonTextSize: '',
      ButtonText: '',
      TextColor: '#62b4ff',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      ImageWidth: '85',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Height: '',
      Source: 'refer-a-friend.svg',
      Icon: '',
      ShowIcon: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createBaseComponentTwo(plainText: any): any {
    return this.fb.group({
      id: '',
      component: 'plainText',
      Text: '',
      TextSize: '16',
      TextAlignment: 'start',
      ButtonTextSize: '',
      ButtonText: '',
      TextColor: '#62b4ff',
      FontWeight: '500',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Height: '',
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: 'I am a plainText description...',
        TextColor: '#ffffff',
        BackgroundColor: '',
        FontSize: '16',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createDynamicHeadline(headline: any): any {
    return this.fb.group({
      id: 1,
      component: 'h1',
      Text: 'Headline',
      TextSize: '32',
      TextAlignment: 'start',
      ButtonTextSize: '',
      ButtonText: '',
      TextColor: '#62b4ff',
      FontWeight: '700',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Height: '',
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createHeadlineTwo(headline: any): any {
    return this.fb.group({
      id: 1,
      component: 'h2',
      Text: 'Headline h2',
      TextSize: '28',
      TextAlignment: 'start',
      ButtonTextSize: '',
      ButtonText: '',
      TextColor: '#62b4ff',
      FontWeight: '700',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Height: '',
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createHeadlineThree(headline: any): any {
    return this.fb.group({
      id: 1,
      component: 'h3',
      Text: 'Headline h3',
      TextSize: '20',
      TextAlignment: 'start',
      ButtonTextSize: '',
      ButtonText: '',
      TextColor: '#62b4ff',
      FontWeight: '700',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Height: '',
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createDynamicButton(button: any): any {
    return this.fb.group({
      id: 1,
      component: 'primaryButton',
      Text: 'Login',
      ButtonText: '',
      TextSize: '16',
      TextAlignment: 'center',
      ButtonTextSize: '',
      TextColor: '#ffffff',
      FontWeight: '700',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '9999',
      Padding: this.fb.group({
        top: 10,
        right: 20,
        bottom: 10,
        left: 20,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createDynamicInput(slimEntry: any): any {
    return this.fb.group({
      id: 1,
      component: 'slimEntry',
      Text: '',
      TextAlignment: 'start',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: true,
        IsPassword: false,
        Borderless: true,
        Input: 'FieldName Default',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createSlimEditor(slimEditor: any): any {
    return this.fb.group({
      id: 1,
      component: 'slimEditor',
      Text: '',
      TextAlignment: 'start',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: true,
        Label: '',
        Input: 'Slim Editor Default',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: false,
        Borderless: true,
        Input: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createDynamicDropdown(dropdown: any): any {
    return this.fb.group({
      id: 1,
      component: 'dropdown',
      Text: '',
      TextAlignment: '',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: true,
        IsRequired: false,
        IsPassword: false,
        GroupName: '',
        Borderless: 'standard',
        Label: 'Label Default',
        SelectedItem: '',
        OptionOne: 'Option one',
        OptionTwo: 'Option two...',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: 'Cancel Default',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: false,
        Column1Config: this.fb.group({
          HorizontalOptions: '',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: '',
        }),
        leftIcon: '',
        rightIcon: '',
        logo: 'blank.png',
      }),
    });
  }

  public createAppHeader(dropdown: any): any {
    return this.fb.group({
      id: 1,
      component: 'appHeader',
      Text: '',
      TextAlignment: '',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '50',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '',
        BackgroundColor: '',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: true,
        Column1Config: this.fb.group({
          HorizontalOptions: 'Start',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: 'End',
        }),
        leftIcon: 'chevron_left',
        rightIcon: 'chevron_right',
        logo: 'crowdtap-logo-white.svg',
      }),
    });
  }

  public createSpacer(spacer: any): any {
    return this.fb.group({
      id: 1,
      component: 'spacer',
      Text: '',
      TextAlignment: '',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: '',
        DetailText: '',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: true,
        Height: '50',
        BackgroundColor: '#900',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: true,
        Column1Config: this.fb.group({
          HorizontalOptions: 'Start',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: 'End',
        }),
        leftIcon: 'chevron_left',
        rightIcon: 'chevron_right',
        logo: 'crowdtap-logo-white.svg',
      }),
    });
  }

  public createExpandingText(expandingText: any): any {
    return this.fb.group({
      id: 1,
      component: 'expandingText',
      Text: '',
      TextAlignment: '',
      ButtonText: '',
      TextSize: '',
      ButtonTextSize: '',
      TextColor: '',
      FontWeight: '',
      ButtonTextColor: '',
      BackgroundColor: '',
      Width: '',
      Height: '',
      ImageWidth: '',
      ImageHeight: '',
      FullBleedHorizontal: false,
      Source: 'blank.png',
      Icon: '',
      ShowIcon: '',
      CornerRadius: '',
      Padding: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      Margin: this.fb.group({
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
      }),
      CommandName: '',
      CommandParameter: '',
      expandingText: this.fb.group({
        HeaderText: 'HeaderText',
        DetailText: 'Detail texty text',
      }),
      plainText: this.fb.group({
        Text: '',
        TextColor: '',
        BackgroundColor: '',
        FontSize: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      spacer: this.fb.group({
        display: false,
        Height: '50',
        BackgroundColor: '#900',
      }),
      slimEditor: this.fb.group({
        display: false,
        Label: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Margin: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      slimEntry: this.fb.group({
        display: false,
        IsPassword: '',
        Borderless: '',
        Input: '',
        Placeholder: '',
        BackgroundColor: '',
        InputBackgroundColor: '',
        TextColor: '',
        PlaceholderColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      dropDown: this.fb.group({
        display: false,
        IsRequired: false,
        GroupName: '',
        Borderless: '',
        Label: '',
        SelectedItem: '',
        OptionOne: '',
        OptionTwo: '',
        TextColor: '',
        BackgroundColor: '',
        DropdownCancelText: '',
        ButtonBackgroundColor: '',
        Padding: this.fb.group({
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
        }),
      }),
      appHeader: this.fb.group({
        display: true,
        Column1Config: this.fb.group({
          HorizontalOptions: 'Start',
        }),
        Column2Config: this.fb.group({
          HorizontalOptions: 'End',
        }),
        leftIcon: 'chevron_left',
        rightIcon: 'chevron_right',
        logo: 'crowdtap-logo-white.svg',
      }),
    });
  }

  // Submit full configuration information
  sendConfig(
    headerConfig: any,
    viewConfig: any,
    visualConfig: any,
    supress: boolean,
    configName: string
  ): Observable<any> {
    const body = {
      ScreenStorageKey: null,
      ScreenName: null,
      ScreenParameter: null,
      SuppressPersist: supress,
      AutomaticDownload: false,
      IsMenuSupported: true,
      DisableCellReuse: false,
      Lifetime: 0,
      DownloadedUTC: null,
      CacheUntilUTC: null,
      ExpireUTC: null,
      InvalidatedUTC: null,
      ScreenNavigationData: null,
      VisualConfig: visualConfig,
      ViewConfigs: viewConfig,
      HeaderConfigs: headerConfig,
      FooterConfigs: [],
      BeforeShowCommands: [],
      AfterShowCommands: [],
      DownloadCommands: [],
      MenuConfigs: [
        {
          is_selected: false,
          identifier: 'main.home',
          is_icon: true,
          icon_character: '',
          label: 'Home',
          command: 'app.navigate.push',
          command_parameter: 'dashboard',
          ui_suppressed: false,
        },
        {
          is_selected: false,
          identifier: 'main.tests',
          is_icon: true,
          icon_character: '',
          label: 'Tests',
          command: 'app.navigate.push',
          command_parameter: 'test.list.v1',
          ui_suppressed: false,
        },
        {
          is_selected: false,
          identifier: 'main.glossary',
          is_icon: true,
          icon_character: '',
          label: 'Glossary',
          command: 'app.navigate.push',
          command_parameter: 'dictionary.overview.v1',
          ui_suppressed: false,
        },
        {
          is_selected: true,
          identifier: 'main.help',
          is_icon: true,
          icon_character: '',
          label: 'Help',
          command: 'app.navigate.push',
          command_parameter: 'help.overview.v1',
          ui_suppressed: false,
        },
        {
          is_selected: false,
          identifier: 'main.settings',
          is_icon: true,
          icon_character: '',
          label: 'Account',
          command: 'app.navigate.push',
          command_parameter: 'settings.overview.v1',
          ui_suppressed: false,
        },
      ],
      Claims: [],
    };

    const call = this.http
      .post<any>(
        this.apiURL + FINAL + configName,
        JSON.stringify(body),
        this.httpOptions
      )
      .pipe(catchError(this.errorHandler));

    this.toasty.show('Screen Sent!', {
      theme: 'snackbar',
      icon: '🤘',
      position: 'bottom-center',
    });

    return call;
  }

  // Error Handler
  errorHandler(error: {
    error: { message: string };
    status: any;
    message: any;
  }) {
    let errorMessage = '';

    if (error.error instanceof ErrorEvent) {
      errorMessage = error.error.message;
    } else {
      errorMessage = `Error Code: ${error.status}\nMessage: ${error.message}`;
    }

    return throwError(() => errorMessage);
  }
}
